### ISSUE TITLE
No license listed.

### ISSUE THREAD

**Issue by Celti** [bkeepers/morphine#4]
This project does not have a listed copyright or LICENSE or COPYING file. Most Linux distributions trying to package software require a license to be specified for each package.

As you say you are extracting the dependency injection features from Gaug.es, and all official and public libraries of theirs I can find are MIT-licensed, I am assuming for the time being (for packaging purposes) that this is also MIT-licensed, but would appreciate clarification.

**Comment by codesoda** [comment]
@bkeepers When you say 'extracting the dependency injection features from Gaug.es' do you mean extracting IOC features into this nice simple ruby implementation or you are removing and stopping using dependency injection from gauges?

**Comment by bkeepers** [comment]
Fixed in d2aac5146bbcd624bc69b4c560c14dfd341e07c1

> When you say 'extracting the dependency injection features from Gaug.es' do you mean extracting IOC features into this nice simple ruby implementation or you are removing and stopping using dependency injection from gauges?

The former. I don't work on gauges anymore, but the last time I did, it still used this pattern.
